# Generated by Django 2.2 on 2019-12-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_image'),
        ('user', '0004_auto_20191210_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='books',
            field=models.ManyToManyField(through='user.Read', to='book.Book'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='Profile_pics'),
        ),
    ]
